import "~/styles/globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Poppins, Offside, Jersey_25, Space_Mono } from "next/font/google";
import { type Metadata, Viewport } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

const font = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-potta-one",
});

export const metadata: Metadata = {
  title: "Bobobo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const viewport: Viewport = {
  width: 1200,
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        // className={`${poppins.className}`}

        className={`${font.className}`}
      >
        <body className="min-h-screen text-gray-700">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
